name: Deploy Flask app to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "."
          target: "/home/azureuser/db-cloud-lab"
          overwrite: true

      - name: Restart Flask app on VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/db-cloud-lab/db-laba
            echo "Stopping old app if running..."
            pkill -f gunicorn || true
            echo "Starting Gunicorn..."
            nohup gunicorn app:app --bind=0.0.0.0:1401 > /home/azureuser/app.log 2>&1 &
            echo "âœ… Deployment complete!"
