name: Deploy Flask app to Azure VM and Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy_webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (для базової перевірки)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C88CFF2E1EFA451389732966AE83A5F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11E2AA423EEF46EE8F87FD6390AC9F3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E15C5450E60343F2AF8F51A965833AC0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-app-lab'
          slot-name: 'Production'
          package: .

  deploy_vm:
    runs-on: ubuntu-latest
    needs: deploy_webapp     

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy project files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "./"
          target: "/home/azureuser/db-cloud-lab"
          overwrite: true
          rm: true

      - name: Restart Flask app on VM (gunicorn)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/azureuser/db-cloud-lab/db-laba
            echo "Stopping old app if running..."
            pkill -f gunicorn || true
            echo "Starting Gunicorn..."
            /home/azureuser/.local/bin/gunicorn app:app --bind=0.0.0.0:1401 --daemon
            echo "✅ VM deployment complete!"
